### PR TITLE
changes for latest errbit compability

### PR DESCRIPTION
**Pull request by Astarodubtcev**

### CODE REVIEW

**Comment by veverkap** [comment]
It would be really great to get this merged.

**Comment by Astarodubtcev** [comment]
You can get it from https://github.com/Astarodubtcev/errbit_pivotal_plugin.git branch 0.4

11.08.2015, 04:50, "Patrick Veverka" notifications@github.com:

**Comment by veverkap** [comment]
@Astarodubtcev that's what I ended up doing, but preferred using the RubyGems version long term.

Thanks for your fix on that.

**Comment by stevecrozz** [comment]
Thanks @veverkap . Let me know if you're interested in helping to maintain this plugin.

**Comment by stevecrozz** [comment]
Just released v0.4.0 with your changes: https://rubygems.org/gems/errbit_pivotal_plugin/versions/0.4.0

**Pull request merged**
